version: "3"
services:
  db:
    image: 461691961615.dkr.ecr.us-east-2.amazonaws.com/oracle/database:19.3.0-ee
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./oradata:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=pwd
      - ORACLE_PDB=pdb
      - ORACLE_SID=sid
